job-defaults: &job-defaults
  working_directory: &working_directory
    ~/app
  environment:
    - RELEASE_BRANCH: vgs-edition
    - AWS_DEFAULT_REGION: us-west-2
    - AWS_REGION: us-west-2
    - AWS_ACCOUNT_ID: "883127560329"
    - AWS_PROFILE: dev/vault
    - VGS_DEV_ARTIFACT_BUCKET: vault-dev-01-audits-01-artifact-19k6160zpr44j

# Set up AWS environment
setup-env: &setup-env
  run:
    name: Setup Environment
    command: |
      ./scripts/env.sh
#      ./scripts/setup-maven-m2-mirrors.sh

# Template to save Maven dependency cache to restore it in another jobs
save-maven-cache: &save-maven-cache
  save_cache:
    key: LittleProxy-{{ .Environment.CACHE_VERSION }}-{{ checksum "pom.xml" }}
    paths:
      - ~/.m2

restore-maven-cache: &restore-maven-cache
  restore_cache:
    key: LittleProxy-{{ .Environment.CACHE_VERSION }}-{{ checksum "pom.xml" }}

# Persists workspace so it can be attached in another jobs as soon as it was checked out and built
persist-workspace: &persist-workspace
  persist_to_workspace:
    root: .
    paths: "*"

attach-workspace: &attach-workspace
  attach_workspace:
    at: *working_directory

machine-setup: &machine-setup
  machine:
    docker_layer_caching: true
    image: ubuntu-2204:2022.04.1

# === JOBS ===
version: 2.1
jobs:
  build:
    <<: *machine-setup
    <<: *job-defaults
    steps:
      - checkout
      - <<: *setup-env
      - <<: *restore-maven-cache
      - run:
          name: Maven Clean Package
          command: docker-compose run build
      - <<: *save-maven-cache
      - <<: *persist-workspace

  test:
    <<: *job-defaults
    docker:
    - image: quay.io/verygoodsecurity/circle-java8-brotli:latest
      auth:
        username: $QUAY_DOCKER_LOGIN
        password: $QUAY_DOCKER_LOGIN_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - <<: *attach-workspace
      - <<: *restore-maven-cache
      - run:
          name: Run test
          command: |
            unset AWS_ACCESS_KEY_ID; unset AWS_SECRET_ACCESS_KEY; ./scripts/run_circle_tests.sh
      - run:
          name: Collect Licenses
          command: unset AWS_ACCESS_KEY_ID; unset AWS_SECRET_ACCESS_KEY; mvn license:aggregate-third-party-report
      - store_artifacts:
          path: target/site/aggregate-third-party-report.html

  deployment:
    <<: *machine-setup
    <<: *job-defaults
    steps:
      - <<: *attach-workspace
      - <<: *restore-maven-cache
      - <<: *setup-env
      - run:
          name: Deploy
          command: |
            unset AWS_ACCESS_KEY_ID; unset AWS_SECRET_ACCESS_KEY; mvn deploy -DskipTests=true
  release:
    <<: *machine-setup
    <<: *job-defaults
    steps:
      - <<: *attach-workspace
      - <<: *restore-maven-cache
      - <<: *setup-env
      - add_ssh_keys:
          fingerprints:
          - "7a:20:4d:b8:d1:0a:47:95:31:ce:2a:22:5e:aa:f6:3d"
      - run:
          name: Release
          command: |
            unset AWS_ACCESS_KEY_ID
            unset AWS_SECRET_ACCESS_KEY
            git config user.name "circleci"
            git config user.email "circleci@vgs.com"
            git fetch
            git checkout $RELEASE_BRANCH
            git pull origin $RELEASE_BRANCH
            git reset --hard
            git tag -d $CIRCLE_TAG
            mvn -B -X -e gitflow:release-start -DreleaseVersion=$CIRCLE_TAG
            mvn -B -X -e gitflow:release-finish -DreleaseVersion=$CIRCLE_TAG -DpostReleaseGoals='deploy -DskipTests'
            git push origin $RELEASE_BRANCH

# === WORKFLOW ===
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build:
          context: circleci
          filters:
            tags:
              only: /.*/
      - test:
          context: artifact-publisher
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deployment:
          context: artifact-publisher
          requires:
            - test
          filters:
            branches:
              only: vgs-edition
      - release:
          context: artifact-publisher
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
